# Conclusion

Since 1990, it is estimated that 420 million hectares of forest have been lost through conversion to other land uses, although the rate of deforestation has decreased over the past three decades.
Apart from South America and Africa all other continents have shown stability in their forest cover regions.


Many countries have started initiatives to increase Forest Cover in barren areas. There is no empirical evidence that these initiatives have had a negative effect on the economies of those countries. Two of the the fastest growing large economies in the world, India and China, have seen large percentage increase in their forest covers while maintaining their growing economy. 
On the other hand,  there are a few countries like Canada which have seen significant deforestation while continuing to grow their economies.


Thus, we conclude that there is no direct correlation between rates of deforestation and GDP growth. This means that it is not necessary for a developing country to overlook ecological balance just for the sake of economic growth as it is possible to grow the economy while maintaining green cover.